### PR TITLE
Views added for login, register, homepage

### PR DESCRIPTION
**Pull request by sukhdeep917**
Status are changed on button click, drop down will be added in new version.

### CODE REVIEW

**Review by kajol184 — APPROVED** [review]
Looks Good To Me 👍

**Review by nirutasubedi01 — APPROVED** [review]
IT WORKED WELL

**Review by Ganeshalingam-Abiram — APPROVED** [review]
Looks fine 💯

**Review by milan1750 — APPROVED** [review]
Looks good, Well done  :+1:

**Pull request merged**
